apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-express-oauth-materialui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-express-oauth-materialui
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: react-express-oauth-materialui
    spec:
      containers:
        - name: react-express-oauth-materialui
          image: react-express-oauth-materialui:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
          envFrom:
            - secretRef:
                name: react-express-oauth-materialui-app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: react-express-oauth-materialui-service
spec:
  selector:
    app: react-express-oauth-materialui
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: react-express-oauth-materialui-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: react-express-oauth-materialui-service
              servicePort: http
