apiVersion: v1
kind: Service
metadata:
  name: react-express-oauth-materialui-service
spec:
  selector:
    app: react-express-oauth-materialui
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer